Nucleo-base adicionada na posicao 0 da sequencia!
a 
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 13 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 11 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 18 da sequencia!
Nucleo-base adicionada na posicao 23 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 18 da sequencia!
Nucleo-base adicionada na posicao 24 da sequencia!
Nucleo-base adicionada na posicao 25 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 18 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 24 da sequencia!
Nucleo-base adicionada na posicao 15 da sequencia!
Nucleo-base adicionada na posicao 13 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 29 da sequencia!
Nucleo-base adicionada na posicao 5 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
a t c g c g g t a g a t c - c t a g a t g g c g c t a 
Nucleo-base adicionada na posicao 29 da sequencia!
Nucleo-base adicionada na posicao 15 da sequencia!
Nucleo-base adicionada na posicao 20 da sequencia!
Nucleo-base adicionada na posicao 39 da sequencia!
Nucleo-base adicionada na posicao 30 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 27 da sequencia!
Nucleo-base adicionada na posicao 33 da sequencia!
Nucleo-base adicionada na posicao 46 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 6 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 22 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 48 da sequencia!
Nucleo-base adicionada na posicao 11 da sequencia!
Nucleo-base adicionada na posicao 33 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 59 da sequencia!
Nucleo-base adicionada na posicao 30 da sequencia!
Nucleo-base adicionada na posicao 16 da sequencia!
Nucleo-base adicionada na posicao 17 da sequencia!
Nucleo-base adicionada na posicao 66 da sequencia!
Nucleo-base adicionada na posicao 46 da sequencia!
Nucleo-base adicionada na posicao 61 da sequencia!
Nucleo-base adicionada na posicao 42 da sequencia!
Nucleo-base adicionada na posicao 35 da sequencia!
Nucleo-base adicionada na posicao 57 da sequencia!
Nucleo-base adicionada na posicao 54 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 55 da sequencia!
Nucleo-base adicionada na posicao 65 da sequencia!
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 32 da sequencia!
Nucleo-base adicionada na posicao 5 da sequencia!
a c a g a g g c > 23
Nucleo-base adicionada na posicao 76 da sequencia!
Nucleo-base adicionada na posicao 16 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 55 da sequencia!
Nucleo-base adicionada na posicao 17 da sequencia!
Nucleo-base adicionada na posicao 81 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 38 da sequencia!
Nucleo-base adicionada na posicao 80 da sequencia!
Nucleo-base adicionada na posicao 66 da sequencia!
Nucleo-base adicionada na posicao 16 da sequencia!
Nucleo-base adicionada na posicao 65 da sequencia!
Nucleo-base adicionada na posicao 87 da sequencia!
Nucleo-base adicionada na posicao 31 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 92 da sequencia!
Nucleo-base adicionada na posicao 69 da sequencia!
Nucleo-base adicionada na posicao 27 da sequencia!
Nucleo-base adicionada na posicao 37 da sequencia!
Nucleo-base adicionada na posicao 87 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 13 da sequencia!
Nucleo-base adicionada na posicao 50 da sequencia!
Nucleo-base adicionada na posicao 54 da sequencia!
Nucleo-base adicionada na posicao 58 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 38 da sequencia!
Nucleo-base adicionada na posicao 108 da sequencia!
Nucleo-base adicionada na posicao 99 da sequencia!
Nucleo-base adicionada na posicao 87 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 107 da sequencia!
Nucleo-base adicionada na posicao 34 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 25 da sequencia!
Nucleo-base adicionada na posicao 102 da sequencia!
Nucleo-base adicionada na posicao 36 da sequencia!
a t t g c c t g a a a t a c t g a t c c a a g g a - a g g a a c c t a g t c a t a a a g t c c g t t a 
Nucleo-base adicionada na posicao 103 da sequencia!
Nucleo-base adicionada na posicao 77 da sequencia!
Nucleo-base adicionada na posicao 17 da sequencia!
Nucleo-base adicionada na posicao 101 da sequencia!
Nucleo-base adicionada na posicao 24 da sequencia!
Nucleo-base adicionada na posicao 27 da sequencia!
Nucleo-base adicionada na posicao 49 da sequencia!
Nucleo-base adicionada na posicao 122 da sequencia!
Nucleo-base adicionada na posicao 109 da sequencia!
Nucleo-base adicionada na posicao 110 da sequencia!
Nucleo-base adicionada na posicao 121 da sequencia!
Nucleo-base adicionada na posicao 100 da sequencia!
Nucleo-base adicionada na posicao 64 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 43 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 101 da sequencia!
Nucleo-base adicionada na posicao 93 da sequencia!
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 32 da sequencia!
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 113 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 103 da sequencia!
Nucleo-base adicionada na posicao 35 da sequencia!
Nucleo-base adicionada na posicao 90 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 43 da sequencia!
Nucleo-base adicionada na posicao 121 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 78 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 149 da sequencia!
Nucleo-base adicionada na posicao 25 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 85 da sequencia!
Nucleo-base adicionada na posicao 141 da sequencia!
Nucleo-base adicionada na posicao 102 da sequencia!
a g g c g a t a c g c g t g t c a g t c a t a a a g g g t c c g t a t a c g c t g g c t g a a g c c a c t t t c t c g t t t t g a a c a c a c t t c g t c c g t a t c c g g c c a t a c a a g g c c t c g t c g t a g a a t t t g t a g g a c c a t g g a g g t t c a g g a g a c t t t c a c c g a a a g a c c c t a c t t a t 
Sistema encerrado.
