Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 6 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 11 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 11 da sequencia!
Nucleo-base adicionada na posicao 15 da sequencia!
Nucleo-base adicionada na posicao 18 da sequencia!
Nucleo-base adicionada na posicao 5 da sequencia!
Nucleo-base adicionada na posicao 11 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 13 da sequencia!
Nucleo-base adicionada na posicao 19 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 19 da sequencia!
Nucleo-base adicionada na posicao 16 da sequencia!
Nucleo-base adicionada na posicao 16 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 33 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 24 da sequencia!
Nucleo-base adicionada na posicao 35 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 36 da sequencia!
Nucleo-base adicionada na posicao 30 da sequencia!
a g a t t c t c t c g a a c c - c c a a g c t c t c t t a g a 
Nucleo-base adicionada na posicao 31 da sequencia!
Nucleo-base adicionada na posicao 22 da sequencia!
Nucleo-base adicionada na posicao 44 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 38 da sequencia!
Nucleo-base adicionada na posicao 35 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 49 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 26 da sequencia!
Nucleo-base adicionada na posicao 52 da sequencia!
Nucleo-base adicionada na posicao 22 da sequencia!
Nucleo-base adicionada na posicao 19 da sequencia!
Nucleo-base adicionada na posicao 6 da sequencia!
Nucleo-base adicionada na posicao 39 da sequencia!
Nucleo-base adicionada na posicao 33 da sequencia!
Nucleo-base adicionada na posicao 35 da sequencia!
Nucleo-base adicionada na posicao 11 da sequencia!
Nucleo-base adicionada na posicao 37 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 26 da sequencia!
Nucleo-base adicionada na posicao 16 da sequencia!
Nucleo-base adicionada na posicao 24 da sequencia!
Nucleo-base adicionada na posicao 24 da sequencia!
Nucleo-base adicionada na posicao 61 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 27 da sequencia!
Nucleo-base adicionada na posicao 38 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 55 da sequencia!
Nucleo-base adicionada na posicao 63 da sequencia!
Nucleo-base adicionada na posicao 59 da sequencia!
Nucleo-base adicionada na posicao 63 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 61 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 79 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 34 da sequencia!
a g a a c t c c c a t t g c t g g t a g a t c a c g c c t g a a a t t g t t t c a a t a a g t c g t c t c c g a a a a g g c g t a g c t g a c t t t t c a g a c g c t 
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 60 da sequencia!
Nucleo-base adicionada na posicao 72 da sequencia!
Nucleo-base adicionada na posicao 66 da sequencia!
Nucleo-base adicionada na posicao 39 da sequencia!
Nucleo-base adicionada na posicao 28 da sequencia!
Nucleo-base adicionada na posicao 27 da sequencia!
Nucleo-base adicionada na posicao 29 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 45 da sequencia!
Nucleo-base adicionada na posicao 80 da sequencia!
Nucleo-base adicionada na posicao 84 da sequencia!
Nucleo-base adicionada na posicao 46 da sequencia!
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 85 da sequencia!
Nucleo-base adicionada na posicao 84 da sequencia!
Nucleo-base adicionada na posicao 80 da sequencia!
Nucleo-base adicionada na posicao 96 da sequencia!
Nucleo-base adicionada na posicao 54 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 90 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 26 da sequencia!
Nucleo-base adicionada na posicao 31 da sequencia!
Nucleo-base adicionada na posicao 81 da sequencia!
Nucleo-base adicionada na posicao 64 da sequencia!
Nucleo-base adicionada na posicao 46 da sequencia!
Nucleo-base adicionada na posicao 106 da sequencia!
Nucleo-base adicionada na posicao 34 da sequencia!
Nucleo-base adicionada na posicao 68 da sequencia!
Nucleo-base adicionada na posicao 26 da sequencia!
Nucleo-base adicionada na posicao 37 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 95 da sequencia!
Nucleo-base adicionada na posicao 21 da sequencia!
Nucleo-base adicionada na posicao 110 da sequencia!
Nucleo-base adicionada na posicao 74 da sequencia!
Nucleo-base adicionada na posicao 94 da sequencia!
Nucleo-base adicionada na posicao 78 da sequencia!
Nucleo-base adicionada na posicao 86 da sequencia!
Nucleo-base adicionada na posicao 86 da sequencia!
a a g a t t c g c < 45
Nucleo-base adicionada na posicao 108 da sequencia!
Nucleo-base adicionada na posicao 54 da sequencia!
Nucleo-base adicionada na posicao 5 da sequencia!
Nucleo-base adicionada na posicao 108 da sequencia!
Nucleo-base adicionada na posicao 117 da sequencia!
Nucleo-base adicionada na posicao 112 da sequencia!
Nucleo-base adicionada na posicao 121 da sequencia!
Nucleo-base adicionada na posicao 76 da sequencia!
Nucleo-base adicionada na posicao 101 da sequencia!
Nucleo-base adicionada na posicao 92 da sequencia!
Nucleo-base adicionada na posicao 65 da sequencia!
Nucleo-base adicionada na posicao 111 da sequencia!
Nucleo-base adicionada na posicao 120 da sequencia!
Nucleo-base adicionada na posicao 78 da sequencia!
Nucleo-base adicionada na posicao 72 da sequencia!
Nucleo-base adicionada na posicao 34 da sequencia!
Nucleo-base adicionada na posicao 82 da sequencia!
Nucleo-base adicionada na posicao 102 da sequencia!
Nucleo-base adicionada na posicao 118 da sequencia!
Nucleo-base adicionada na posicao 82 da sequencia!
Nucleo-base adicionada na posicao 45 da sequencia!
Nucleo-base adicionada na posicao 81 da sequencia!
Nucleo-base adicionada na posicao 19 da sequencia!
Nucleo-base adicionada na posicao 122 da sequencia!
Nucleo-base adicionada na posicao 39 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 124 da sequencia!
Nucleo-base adicionada na posicao 88 da sequencia!
Nucleo-base adicionada na posicao 120 da sequencia!
Nucleo-base adicionada na posicao 110 da sequencia!
Nucleo-base adicionada na posicao 18 da sequencia!
Nucleo-base adicionada na posicao 35 da sequencia!
Nucleo-base adicionada na posicao 15 da sequencia!
Nucleo-base adicionada na posicao 81 da sequencia!
Nucleo-base adicionada na posicao 5 da sequencia!
Nucleo-base adicionada na posicao 54 da sequencia!
Nucleo-base adicionada na posicao 100 da sequencia!
Nucleo-base adicionada na posicao 5 da sequencia!
Nucleo-base adicionada na posicao 21 da sequencia!
Nucleo-base adicionada na posicao 148 da sequencia!
Nucleo-base adicionada na posicao 64 da sequencia!
Nucleo-base da posicao 39 removida!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 130 da sequencia!
Nucleo-base adicionada na posicao 45 da sequencia!
Nucleo-base adicionada na posicao 26 da sequencia!
Nucleo-base adicionada na posicao 162 da sequencia!
Nucleo-base adicionada na posicao 89 da sequencia!
Nucleo-base adicionada na posicao 38 da sequencia!
Nucleo-base adicionada na posicao 110 da sequencia!
Nucleo-base adicionada na posicao 157 da sequencia!
Nucleo-base adicionada na posicao 151 da sequencia!
Nucleo-base adicionada na posicao 43 da sequencia!
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 124 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 158 da sequencia!
Nucleo-base adicionada na posicao 91 da sequencia!
Nucleo-base adicionada na posicao 111 da sequencia!
Nucleo-base adicionada na posicao 20 da sequencia!
Nucleo-base adicionada na posicao 119 da sequencia!
Nucleo-base adicionada na posicao 113 da sequencia!
Nucleo-base adicionada na posicao 15 da sequencia!
Nucleo-base adicionada na posicao 92 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 45 da sequencia!
Nucleo-base adicionada na posicao 96 da sequencia!
Nucleo-base adicionada na posicao 61 da sequencia!
Nucleo-base adicionada na posicao 38 da sequencia!
Nucleo-base adicionada na posicao 121 da sequencia!
Nucleo-base adicionada na posicao 105 da sequencia!
Nucleo-base adicionada na posicao 88 da sequencia!
Nucleo-base adicionada na posicao 51 da sequencia!
Nucleo-base adicionada na posicao 167 da sequencia!
Nucleo-base adicionada na posicao 186 da sequencia!
Nucleo-base adicionada na posicao 74 da sequencia!
Nucleo-base adicionada na posicao 95 da sequencia!
Nucleo-base adicionada na posicao 65 da sequencia!
Nucleo-base adicionada na posicao 53 da sequencia!
Nucleo-base adicionada na posicao 188 da sequencia!
Nucleo-base adicionada na posicao 201 da sequencia!
Nucleo-base adicionada na posicao 180 da sequencia!
Nucleo-base adicionada na posicao 111 da sequencia!
c a g t a g g t t c a g t c g a t c g c g t g a g t c c g a > 28
Nucleo-base adicionada na posicao 106 da sequencia!
Nucleo-base adicionada na posicao 98 da sequencia!
Nucleo-base adicionada na posicao 161 da sequencia!
Nucleo-base adicionada na posicao 42 da sequencia!
Nucleo-base adicionada na posicao 71 da sequencia!
Nucleo-base adicionada na posicao 129 da sequencia!
Nucleo-base adicionada na posicao 110 da sequencia!
Nucleo-base adicionada na posicao 117 da sequencia!
Nucleo-base adicionada na posicao 75 da sequencia!
Nucleo-base adicionada na posicao 13 da sequencia!
Nucleo-base adicionada na posicao 181 da sequencia!
Nucleo-base adicionada na posicao 117 da sequencia!
Nucleo-base adicionada na posicao 98 da sequencia!
Nucleo-base adicionada na posicao 142 da sequencia!
Nucleo-base adicionada na posicao 127 da sequencia!
Nucleo-base adicionada na posicao 125 da sequencia!
Nucleo-base adicionada na posicao 105 da sequencia!
Nucleo-base adicionada na posicao 6 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 165 da sequencia!
Nucleo-base adicionada na posicao 147 da sequencia!
Nucleo-base adicionada na posicao 218 da sequencia!
Nucleo-base adicionada na posicao 144 da sequencia!
Nucleo-base adicionada na posicao 95 da sequencia!
Nucleo-base adicionada na posicao 72 da sequencia!
Nucleo-base adicionada na posicao 127 da sequencia!
Nucleo-base adicionada na posicao 70 da sequencia!
Nucleo-base adicionada na posicao 45 da sequencia!
Nucleo-base adicionada na posicao 157 da sequencia!
Nucleo-base adicionada na posicao 81 da sequencia!
Nucleo-base adicionada na posicao 34 da sequencia!
Nucleo-base adicionada na posicao 91 da sequencia!
Nucleo-base adicionada na posicao 52 da sequencia!
Nucleo-base adicionada na posicao 26 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 113 da sequencia!
Nucleo-base adicionada na posicao 118 da sequencia!
Nucleo-base adicionada na posicao 24 da sequencia!
Nucleo-base adicionada na posicao 199 da sequencia!
Nucleo-base adicionada na posicao 30 da sequencia!
Nucleo-base adicionada na posicao 156 da sequencia!
c g g c g g a t c g g t t t c c c g t a c a a t a a c a g t g g a a g c t a c g < 59
Nucleo-base adicionada na posicao 117 da sequencia!
Nucleo-base adicionada na posicao 50 da sequencia!
Nucleo-base adicionada na posicao 199 da sequencia!
Nucleo-base adicionada na posicao 150 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 126 da sequencia!
Nucleo-base adicionada na posicao 62 da sequencia!
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 166 da sequencia!
Nucleo-base adicionada na posicao 92 da sequencia!
Nucleo-base adicionada na posicao 241 da sequencia!
Nucleo-base adicionada na posicao 186 da sequencia!
Nucleo-base adicionada na posicao 26 da sequencia!
Nucleo-base adicionada na posicao 163 da sequencia!
Nucleo-base adicionada na posicao 132 da sequencia!
Nucleo-base adicionada na posicao 6 da sequencia!
Nucleo-base adicionada na posicao 102 da sequencia!
Nucleo-base adicionada na posicao 92 da sequencia!
Nucleo-base adicionada na posicao 96 da sequencia!
Nucleo-base adicionada na posicao 150 da sequencia!
Nucleo-base adicionada na posicao 104 da sequencia!
Nucleo-base adicionada na posicao 207 da sequencia!
Nucleo-base adicionada na posicao 234 da sequencia!
Nucleo-base adicionada na posicao 203 da sequencia!
Nucleo-base adicionada na posicao 216 da sequencia!
Nucleo-base adicionada na posicao 199 da sequencia!
Nucleo-base adicionada na posicao 202 da sequencia!
Nucleo-base adicionada na posicao 93 da sequencia!
Nucleo-base adicionada na posicao 67 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 167 da sequencia!
Nucleo-base adicionada na posicao 37 da sequencia!
Nucleo-base adicionada na posicao 183 da sequencia!
Nucleo-base adicionada na posicao 279 da sequencia!
Nucleo-base adicionada na posicao 238 da sequencia!
Nucleo-base adicionada na posicao 255 da sequencia!
Nucleo-base adicionada na posicao 267 da sequencia!
Nucleo-base adicionada na posicao 132 da sequencia!
Nucleo-base adicionada na posicao 205 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 216 da sequencia!
Nucleo-base da posicao 151 removida!
Nucleo-base adicionada na posicao 115 da sequencia!
Nucleo-base adicionada na posicao 196 da sequencia!
Nucleo-base adicionada na posicao 114 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 139 da sequencia!
Nucleo-base adicionada na posicao 270 da sequencia!
Nucleo-base adicionada na posicao 137 da sequencia!
Nucleo-base adicionada na posicao 69 da sequencia!
Nucleo-base adicionada na posicao 259 da sequencia!
Nucleo-base adicionada na posicao 284 da sequencia!
Nucleo-base adicionada na posicao 216 da sequencia!
Nucleo-base adicionada na posicao 176 da sequencia!
Nucleo-base adicionada na posicao 123 da sequencia!
Nucleo-base adicionada na posicao 225 da sequencia!
Nucleo-base adicionada na posicao 174 da sequencia!
Nucleo-base adicionada na posicao 249 da sequencia!
Nucleo-base adicionada na posicao 221 da sequencia!
Nucleo-base adicionada na posicao 168 da sequencia!
Nucleo-base adicionada na posicao 161 da sequencia!
Nucleo-base adicionada na posicao 134 da sequencia!
Nucleo-base adicionada na posicao 97 da sequencia!
Nucleo-base adicionada na posicao 249 da sequencia!
Nucleo-base adicionada na posicao 307 da sequencia!
Nucleo-base adicionada na posicao 111 da sequencia!
Nucleo-base adicionada na posicao 73 da sequencia!
Nucleo-base adicionada na posicao 229 da sequencia!
Nucleo-base adicionada na posicao 215 da sequencia!
Nucleo-base adicionada na posicao 240 da sequencia!
Nucleo-base adicionada na posicao 177 da sequencia!
Nucleo-base adicionada na posicao 112 da sequencia!
Nucleo-base adicionada na posicao 52 da sequencia!
Nucleo-base adicionada na posicao 170 da sequencia!
Nucleo-base adicionada na posicao 218 da sequencia!
Nucleo-base adicionada na posicao 254 da sequencia!
Nucleo-base adicionada na posicao 260 da sequencia!
Nucleo-base adicionada na posicao 192 da sequencia!
Nucleo-base adicionada na posicao 92 da sequencia!
Nucleo-base adicionada na posicao 50 da sequencia!
Nucleo-base adicionada na posicao 172 da sequencia!
Nucleo-base adicionada na posicao 166 da sequencia!
Nucleo-base adicionada na posicao 137 da sequencia!
g g g g g g a g t g c t t c t g a a c a c a t c c c c g a c c c c t a t g c g a c t t g a a g a g t a g a c g g a a t c c t t a g c g g g c g g c t t g c a a c a a t g c g g a g t g t a a a g c a g t a t g c g a a g a c t t g t t c g c a c t g g t c t t c g g c c g g a t c t g g t t a t c c c t t t g g t a c a a c t a a a c a g t g g a a g t c t a t a a c g c a a c t a a g a g a g a t a t c c a a a c g a g a g a t c g a t g c c g t t c c t t t c t t a t a g t t c c a t g g g g g a g a t a t t a g a t c t t t t c g t c g t c c c t t t t t a t t a a a a t c t c t c a a c a t g t a g g t c t c a g t c c g a t a c g g c g t c g c a g t c c g a t g t 
Nucleo-base adicionada na posicao 305 da sequencia!
Nucleo-base adicionada na posicao 79 da sequencia!
Nucleo-base adicionada na posicao 74 da sequencia!
Nucleo-base adicionada na posicao 210 da sequencia!
Nucleo-base adicionada na posicao 141 da sequencia!
Nucleo-base adicionada na posicao 193 da sequencia!
Nucleo-base adicionada na posicao 257 da sequencia!
Nucleo-base adicionada na posicao 153 da sequencia!
Nucleo-base adicionada na posicao 78 da sequencia!
Nucleo-base adicionada na posicao 203 da sequencia!
Nucleo-base adicionada na posicao 211 da sequencia!
Nucleo-base adicionada na posicao 230 da sequencia!
Nucleo-base adicionada na posicao 330 da sequencia!
Nucleo-base adicionada na posicao 333 da sequencia!
Nucleo-base adicionada na posicao 219 da sequencia!
Nucleo-base adicionada na posicao 34 da sequencia!
Nucleo-base adicionada na posicao 36 da sequencia!
Nucleo-base adicionada na posicao 103 da sequencia!
Nucleo-base adicionada na posicao 5 da sequencia!
Nucleo-base adicionada na posicao 322 da sequencia!
Nucleo-base adicionada na posicao 95 da sequencia!
Nucleo-base adicionada na posicao 243 da sequencia!
Nucleo-base adicionada na posicao 180 da sequencia!
Nucleo-base adicionada na posicao 186 da sequencia!
Nucleo-base adicionada na posicao 149 da sequencia!
Nucleo-base adicionada na posicao 351 da sequencia!
Nucleo-base adicionada na posicao 110 da sequencia!
Nucleo-base adicionada na posicao 65 da sequencia!
Nucleo-base adicionada na posicao 82 da sequencia!
Nucleo-base adicionada na posicao 29 da sequencia!
Nucleo-base adicionada na posicao 222 da sequencia!
Nucleo-base adicionada na posicao 326 da sequencia!
Nucleo-base adicionada na posicao 96 da sequencia!
Nucleo-base adicionada na posicao 323 da sequencia!
Nucleo-base adicionada na posicao 300 da sequencia!
Nucleo-base adicionada na posicao 82 da sequencia!
Nucleo-base adicionada na posicao 52 da sequencia!
Nucleo-base adicionada na posicao 23 da sequencia!
Nucleo-base adicionada na posicao 271 da sequencia!
Nucleo-base adicionada na posicao 177 da sequencia!
Nucleo-base adicionada na posicao 237 da sequencia!
Nucleo-base da posicao 324 removida!
Nucleo-base adicionada na posicao 258 da sequencia!
Nucleo-base adicionada na posicao 212 da sequencia!
Nucleo-base adicionada na posicao 117 da sequencia!
Nucleo-base adicionada na posicao 333 da sequencia!
Nucleo-base adicionada na posicao 101 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 50 da sequencia!
Nucleo-base adicionada na posicao 301 da sequencia!
Nucleo-base adicionada na posicao 266 da sequencia!
Nucleo-base adicionada na posicao 30 da sequencia!
Nucleo-base adicionada na posicao 90 da sequencia!
Nucleo-base adicionada na posicao 323 da sequencia!
Nucleo-base adicionada na posicao 115 da sequencia!
Nucleo-base adicionada na posicao 318 da sequencia!
Nucleo-base adicionada na posicao 347 da sequencia!
Nucleo-base adicionada na posicao 133 da sequencia!
Nucleo-base adicionada na posicao 113 da sequencia!
Nucleo-base adicionada na posicao 238 da sequencia!
Nucleo-base adicionada na posicao 123 da sequencia!
Nucleo-base adicionada na posicao 178 da sequencia!
Nucleo-base adicionada na posicao 118 da sequencia!
Nucleo-base adicionada na posicao 116 da sequencia!
Nucleo-base adicionada na posicao 132 da sequencia!
Nucleo-base adicionada na posicao 215 da sequencia!
Nucleo-base adicionada na posicao 63 da sequencia!
Nucleo-base adicionada na posicao 354 da sequencia!
Nucleo-base adicionada na posicao 65 da sequencia!
Nucleo-base adicionada na posicao 267 da sequencia!
Nucleo-base adicionada na posicao 311 da sequencia!
Nucleo-base adicionada na posicao 71 da sequencia!
Nucleo-base adicionada na posicao 285 da sequencia!
Nucleo-base adicionada na posicao 151 da sequencia!
Nucleo-base adicionada na posicao 177 da sequencia!
Nucleo-base adicionada na posicao 246 da sequencia!
Nucleo-base adicionada na posicao 248 da sequencia!
Nucleo-base adicionada na posicao 345 da sequencia!
Nucleo-base adicionada na posicao 288 da sequencia!
Nucleo-base adicionada na posicao 360 da sequencia!
Nucleo-base adicionada na posicao 37 da sequencia!
Nucleo-base adicionada na posicao 81 da sequencia!
Nucleo-base adicionada na posicao 244 da sequencia!
g g g c g g t g a g t g c t t c t g a a c a c a t t c c c c a g c a c c c g c t a a c t g c g a c t t g g a a g a c g t a g a c c g g g a a t c g c t a t a g c g g g g c g g c t g t g g c g c c a a c c a a t g c g g g a c g g t g t a a t a g t c c t a a g t a a t c c g c g c a a g a c a t t g t t c g c a a c t g g t c t t c g g c c g g a t c t g c g c t t g a t c c c t t t a a g g t a c a a c g t a a a c a g t g g a a c g t c t a g t a a c a g c a a c t a a g a g a t a g a t a t c a c c a a a g c g g c g a c g a g a t t c c t g a t g c c g t t a c c g t t t c t t g t a t a a a g t t t c c a t g g g g g t a g a t a t t a g a t t c t t c t t c g t c a g t c c c t t t t t a c c t t a a a a a t t c t c t c a a c a t t a g g g t a t g c t c t a t g t c c g g a a t a c g g c g t c g c a g g t t c c g a t g g t 
Nucleo-base adicionada na posicao 369 da sequencia!
Nucleo-base adicionada na posicao 316 da sequencia!
Nucleo-base adicionada na posicao 111 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
g g g c g g t g a g c t g c t t c t g a a c a c a t t c c c c a g c a c c c g c t a a c t g c g a c t t g g a a g a c g t a g a c c g g g a a t c g c t a t a g c g g g g c g g c t g t g g c g c c a a c c a a t g c g g g a c c g g t g t a a t a g t c c t a a g t a a t c c g c g c a a g a c a t t g t t c g c a a c t g g t c t t c g g c c g g a t c t g c g c t t g a t c c c t t t a a g g t a c a a c g t a a a c a g t g g a a c g t c t a g t a a c a g c a a c t a a g a g a t a g a t a t c a c c a a a g c g g c g a c g a g a t t c c t g a t g c c g t t a c c g t t t c t t g t a t a a a g t t t c c a t g g g g g t a g a t a t t a g a t t t c t t c t t c g t c a g t c c c t t t t t a c c t t a a a a a t t c t c t c a a c a t t a g g g t a t g g c t c t a t g t c c g g a a t a c g g c g t c g c a g g t t c c g a t g g t 
Sistema encerrado.
