Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 6 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 5 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 5 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 17 da sequencia!
Nucleo-base adicionada na posicao 12 da sequencia!
Nucleo-base adicionada na posicao 16 da sequencia!
Nucleo-base adicionada na posicao 19 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 22 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 11 da sequencia!
Nucleo-base adicionada na posicao 26 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 13 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 3 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
a c t t t g a a c c c g t t a c a - a c a t t g c c c a a g t t t c a 
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 31 da sequencia!
Nucleo-base adicionada na posicao 27 da sequencia!
Nucleo-base adicionada na posicao 21 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 24 da sequencia!
Nucleo-base adicionada na posicao 28 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 44 da sequencia!
Nucleo-base adicionada na posicao 17 da sequencia!
Nucleo-base adicionada na posicao 31 da sequencia!
Nucleo-base adicionada na posicao 4 da sequencia!
Nucleo-base adicionada na posicao 32 da sequencia!
Nucleo-base adicionada na posicao 18 da sequencia!
Nucleo-base adicionada na posicao 46 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 29 da sequencia!
Nucleo-base adicionada na posicao 35 da sequencia!
Nucleo-base adicionada na posicao 34 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 41 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 32 da sequencia!
Nucleo-base adicionada na posicao 2 da sequencia!
Nucleo-base adicionada na posicao 44 da sequencia!
Nucleo-base adicionada na posicao 57 da sequencia!
Nucleo-base adicionada na posicao 38 da sequencia!
Nucleo-base adicionada na posicao 29 da sequencia!
Nucleo-base adicionada na posicao 11 da sequencia!
Nucleo-base adicionada na posicao 44 da sequencia!
Nucleo-base adicionada na posicao 39 da sequencia!
Nucleo-base adicionada na posicao 33 da sequencia!
Nucleo-base adicionada na posicao 37 da sequencia!
Nucleo-base adicionada na posicao 46 da sequencia!
Nucleo-base adicionada na posicao 21 da sequencia!
Nucleo-base adicionada na posicao 35 da sequencia!
Nucleo-base adicionada na posicao 21 da sequencia!
Nucleo-base adicionada na posicao 76 da sequencia!
a a a c c c g t a < 6
Nucleo-base adicionada na posicao 61 da sequencia!
Nucleo-base adicionada na posicao 67 da sequencia!
Nucleo-base adicionada na posicao 20 da sequencia!
Nucleo-base adicionada na posicao 72 da sequencia!
Nucleo-base adicionada na posicao 75 da sequencia!
Nucleo-base adicionada na posicao 29 da sequencia!
Nucleo-base adicionada na posicao 83 da sequencia!
Nucleo-base adicionada na posicao 61 da sequencia!
Nucleo-base adicionada na posicao 27 da sequencia!
Nucleo-base adicionada na posicao 87 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 81 da sequencia!
Nucleo-base adicionada na posicao 40 da sequencia!
Nucleo-base adicionada na posicao 79 da sequencia!
Nucleo-base adicionada na posicao 74 da sequencia!
Nucleo-base adicionada na posicao 69 da sequencia!
Nucleo-base adicionada na posicao 65 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 62 da sequencia!
Nucleo-base adicionada na posicao 17 da sequencia!
Nucleo-base adicionada na posicao 75 da sequencia!
Nucleo-base adicionada na posicao 7 da sequencia!
Nucleo-base adicionada na posicao 82 da sequencia!
Nucleo-base adicionada na posicao 31 da sequencia!
Nucleo-base adicionada na posicao 59 da sequencia!
Nucleo-base adicionada na posicao 75 da sequencia!
Nucleo-base adicionada na posicao 28 da sequencia!
Nucleo-base adicionada na posicao 23 da sequencia!
Nucleo-base adicionada na posicao 89 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 84 da sequencia!
Nucleo-base adicionada na posicao 15 da sequencia!
Nucleo-base adicionada na posicao 75 da sequencia!
Nucleo-base adicionada na posicao 28 da sequencia!
Nucleo-base adicionada na posicao 20 da sequencia!
Nucleo-base adicionada na posicao 44 da sequencia!
Nucleo-base adicionada na posicao 23 da sequencia!
Nucleo-base adicionada na posicao 81 da sequencia!
Nucleo-base adicionada na posicao 29 da sequencia!
t g t a g t c g g t a t g c c c t t t a a t c t a g a a g t g g c c c t t a c g c t t a t c a a a t g t t t c c g a a a c c c g t a t g t g t c c t c a c t a t a a a t t a t t t g g c g a c g c a c g a g g t g a c g a t c t t a g c g a 
Nucleo-base adicionada na posicao 96 da sequencia!
Nucleo-base adicionada na posicao 18 da sequencia!
Nucleo-base adicionada na posicao 49 da sequencia!
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 72 da sequencia!
Nucleo-base adicionada na posicao 101 da sequencia!
Nucleo-base adicionada na posicao 117 da sequencia!
Nucleo-base adicionada na posicao 122 da sequencia!
Nucleo-base adicionada na posicao 6 da sequencia!
Nucleo-base adicionada na posicao 59 da sequencia!
Nucleo-base adicionada na posicao 126 da sequencia!
Nucleo-base adicionada na posicao 71 da sequencia!
Nucleo-base adicionada na posicao 16 da sequencia!
Nucleo-base adicionada na posicao 27 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 111 da sequencia!
Nucleo-base adicionada na posicao 23 da sequencia!
Nucleo-base adicionada na posicao 37 da sequencia!
Nucleo-base adicionada na posicao 136 da sequencia!
Nucleo-base adicionada na posicao 130 da sequencia!
Nucleo-base adicionada na posicao 11 da sequencia!
Nucleo-base adicionada na posicao 47 da sequencia!
Nucleo-base adicionada na posicao 125 da sequencia!
Nucleo-base adicionada na posicao 131 da sequencia!
Nucleo-base adicionada na posicao 26 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 37 da sequencia!
Nucleo-base adicionada na posicao 27 da sequencia!
Nucleo-base adicionada na posicao 80 da sequencia!
Nucleo-base adicionada na posicao 55 da sequencia!
Nucleo-base adicionada na posicao 121 da sequencia!
Nucleo-base adicionada na posicao 99 da sequencia!
Nucleo-base adicionada na posicao 130 da sequencia!
Nucleo-base adicionada na posicao 52 da sequencia!
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 140 da sequencia!
Nucleo-base adicionada na posicao 137 da sequencia!
Nucleo-base adicionada na posicao 76 da sequencia!
Nucleo-base adicionada na posicao 154 da sequencia!
t a a a t g t c c g c t t a t g a g t a t c t c a g a a t g t g a g c c c t t a c t t g c t c t a t c c a a a a t g t t > 49
Nucleo-base adicionada na posicao 14 da sequencia!
Nucleo-base adicionada na posicao 57 da sequencia!
Nucleo-base adicionada na posicao 124 da sequencia!
Nucleo-base adicionada na posicao 25 da sequencia!
Nucleo-base adicionada na posicao 132 da sequencia!
Nucleo-base adicionada na posicao 82 da sequencia!
Nucleo-base adicionada na posicao 149 da sequencia!
Nucleo-base adicionada na posicao 131 da sequencia!
Nucleo-base adicionada na posicao 110 da sequencia!
Nucleo-base adicionada na posicao 60 da sequencia!
Nucleo-base adicionada na posicao 16 da sequencia!
Nucleo-base adicionada na posicao 131 da sequencia!
Nucleo-base adicionada na posicao 134 da sequencia!
Nucleo-base adicionada na posicao 89 da sequencia!
Nucleo-base adicionada na posicao 151 da sequencia!
Nucleo-base adicionada na posicao 95 da sequencia!
Nucleo-base adicionada na posicao 89 da sequencia!
Nucleo-base adicionada na posicao 173 da sequencia!
Nucleo-base adicionada na posicao 147 da sequencia!
Nucleo-base adicionada na posicao 167 da sequencia!
Nucleo-base adicionada na posicao 81 da sequencia!
Nucleo-base adicionada na posicao 173 da sequencia!
Nucleo-base adicionada na posicao 61 da sequencia!
Nucleo-base adicionada na posicao 29 da sequencia!
Nucleo-base adicionada na posicao 29 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 63 da sequencia!
Nucleo-base adicionada na posicao 148 da sequencia!
Nucleo-base adicionada na posicao 59 da sequencia!
Nucleo-base adicionada na posicao 64 da sequencia!
Nucleo-base adicionada na posicao 183 da sequencia!
Nucleo-base adicionada na posicao 113 da sequencia!
Nucleo-base adicionada na posicao 95 da sequencia!
Nucleo-base adicionada na posicao 45 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 193 da sequencia!
Nucleo-base adicionada na posicao 9 da sequencia!
Nucleo-base adicionada na posicao 74 da sequencia!
t g t a g t t c c c g g t a g t c t g c c g a a a a c c c g c t t t g a t t g t g g t c c t c a g c t a t t a a a t t a t t t a g g c a g t g g c a t c g t a a a t g t c c g c t t a t g a a g t a a t a c t t g c a g a a c t g t g a g c c c c t t a c t t g c t c c t a t c c a a a a t g t t g t g c t a c t a c g g a a a g g t c g g a c g t g a a t c c t t t a t a g c g c c c t g g a a c t a 
Nucleo-base adicionada na posicao 121 da sequencia!
Nucleo-base adicionada na posicao 194 da sequencia!
Nucleo-base adicionada na posicao 120 da sequencia!
Nucleo-base adicionada na posicao 103 da sequencia!
Nucleo-base adicionada na posicao 197 da sequencia!
Nucleo-base adicionada na posicao 10 da sequencia!
Nucleo-base adicionada na posicao 83 da sequencia!
Nucleo-base adicionada na posicao 136 da sequencia!
Nucleo-base adicionada na posicao 8 da sequencia!
Nucleo-base adicionada na posicao 104 da sequencia!
Nucleo-base adicionada na posicao 111 da sequencia!
Nucleo-base adicionada na posicao 101 da sequencia!
Nucleo-base adicionada na posicao 25 da sequencia!
Nucleo-base adicionada na posicao 129 da sequencia!
Nucleo-base adicionada na posicao 163 da sequencia!
Nucleo-base adicionada na posicao 151 da sequencia!
Nucleo-base adicionada na posicao 162 da sequencia!
Nucleo-base adicionada na posicao 203 da sequencia!
Nucleo-base adicionada na posicao 117 da sequencia!
Nucleo-base adicionada na posicao 152 da sequencia!
Nucleo-base adicionada na posicao 145 da sequencia!
Nucleo-base adicionada na posicao 191 da sequencia!
Nucleo-base adicionada na posicao 182 da sequencia!
Nucleo-base adicionada na posicao 95 da sequencia!
Nucleo-base adicionada na posicao 13 da sequencia!
Nucleo-base adicionada na posicao 46 da sequencia!
Nucleo-base adicionada na posicao 201 da sequencia!
Nucleo-base adicionada na posicao 167 da sequencia!
Nucleo-base adicionada na posicao 186 da sequencia!
Nucleo-base adicionada na posicao 18 da sequencia!
Nucleo-base adicionada na posicao 22 da sequencia!
Nucleo-base adicionada na posicao 163 da sequencia!
Nucleo-base adicionada na posicao 214 da sequencia!
Nucleo-base adicionada na posicao 198 da sequencia!
Nucleo-base adicionada na posicao 42 da sequencia!
Nucleo-base adicionada na posicao 140 da sequencia!
Nucleo-base adicionada na posicao 110 da sequencia!
Nucleo-base adicionada na posicao 66 da sequencia!
Nucleo-base adicionada na posicao 60 da sequencia!
t a c g g a a a g g t c a a g g a c g t g c a a g t c c t t t t a t a g c g g c c c a t g g a a a c c t a - a t c c a a a g g t a c c c g g c g a t a t t t t c c t g a a c g t g c a g g a a c t g g a a a g g c a t 
Nucleo-base adicionada na posicao 68 da sequencia!
Nucleo-base adicionada na posicao 92 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 124 da sequencia!
Nucleo-base adicionada na posicao 18 da sequencia!
Nucleo-base adicionada na posicao 71 da sequencia!
Nucleo-base adicionada na posicao 32 da sequencia!
Nucleo-base adicionada na posicao 61 da sequencia!
Nucleo-base adicionada na posicao 243 da sequencia!
Nucleo-base adicionada na posicao 43 da sequencia!
Nucleo-base adicionada na posicao 161 da sequencia!
Nucleo-base adicionada na posicao 201 da sequencia!
Nucleo-base adicionada na posicao 30 da sequencia!
Nucleo-base adicionada na posicao 32 da sequencia!
Nucleo-base adicionada na posicao 144 da sequencia!
Nucleo-base adicionada na posicao 233 da sequencia!
Nucleo-base adicionada na posicao 229 da sequencia!
Nucleo-base adicionada na posicao 199 da sequencia!
Nucleo-base adicionada na posicao 208 da sequencia!
Nucleo-base adicionada na posicao 35 da sequencia!
Nucleo-base adicionada na posicao 127 da sequencia!
Nucleo-base adicionada na posicao 223 da sequencia!
Nucleo-base adicionada na posicao 206 da sequencia!
Nucleo-base adicionada na posicao 0 da sequencia!
Nucleo-base adicionada na posicao 1 da sequencia!
Nucleo-base adicionada na posicao 96 da sequencia!
Nucleo-base adicionada na posicao 147 da sequencia!
g a a t g t a g t t c g c c c g t g t a a g a t c t g g c c g a c t g a c t a a c c c g c t t t g g a t t t g t g g c t c c t c a g c t t a a t t a a a t a t c t a t t t a g g c a g t g g c a c t c g t a a a g t t g t c c g c t t a a t g a a g t a g a a t a g g c t t t g g c c a g a g a c t g c t g t a g c c c c c c g t a t a c t t g c t c c t c g t a t c c a a g g a a t c g t t g t g t c g t a t c a t c c g a a a g g g a t a t c c c g g c g a t a t t g t t c c t g a a c g a t g c a a g g a a c t g g a a a g g c a t t 
Sistema encerrado.
